import dotenv from "dotenv";
import { StrategyConfig } from "../types/types";
dotenv.config();
export const config_strategy2: StrategyConfig = {
  apiKey: process.env.COPITRADE_API_KEY || "",
  apiSecret: process.env.COPITRADE_API_SECRET || "",
  leverage: 10,
  maxPositions: 25,
  maxRisk: 0.02,
  strategySmaPeriodSlow: 200,
  strategySmaPeriodFast: 50,
  strategyRsiOverbought: 40,
  strategyRsiPeriod: 14,
  strategyStopLossDelta: 0.1,
  strategyTakeProfitDelta: 0.17,
  backtestCandleInterval: 60,
  pauseCandlesAfterLoss: 5,
  symbols: [
    "FLOCKUSDT",
    "EDGEUSDT",
    "DIAUSDT",
    "CLANKERUSDT",
    "FIDAUSDT",
    "LITUSDT",
    "DOODUSDT",
    "POLYXUSDT",
    "PNUTUSDT",
    "BROCCOLIUSDT",
    "LSKUSDT",
    "FOLKSUSDT",
    "CUSDT",
    "GRIFFAINUSDT",
    "PROVEUSDT",
    "EPICUSDT",
    "RONINUSDT",
    "HIVEUSDT",
    "OLUSDT",
    "SAGAUSDT",
    "BLESSUSDT",
    "SEIUSDT",
    "1000FLOKIUSDT",
    "GRASSUSDT",
    "10000QUBICUSDT",
    "HANAUSDT",
    "1000TAGUSDT",
    "CHILLGUYUSDT",
    "EIGENUSDT",
    "SCRTUSDT",
    "AXSUSDT",
    "ARPAUSDT",
    "EGLDUSDT",
    "BOBBOBUSDT",
    "COAIUSDT",
    "DOLOUSDT",
    "NIGHTUSDT",
    "ALTUSDT",
    "ARIAUSDT",
    "BIGTIMEUSDT",
    "ERAUSDT",
    "PHAUSDT",
    "BANANAUSDT",
    "PYRUSDT",
    "BSVUSDT",
    "ADAUSDT",
    "0GUSDT",
    "DRIFTUSDT",
    "PUMPBTCUSDT",
    "1000NEIROCTOUSDT",
    "NOMUSDT",
    "1000CATUSDT",
    "PYTHUSDT",
    "HOLOUSDT",
    "OPENUSDT",
    "OPNUSDT",
    "KASUSDT",
    "GUNUSDT",
    "GLMUSDT",
    "HPOS10IUSDT",
    "LUMIAUSDT",
    "CTCUSDT",
    "ACXUSDT",
    "MIRAUSDT",
    "HIGHUSDT",
    "HYPEUSDT",
    "ASPUSDT",
    "SKRUSDT",
    "HMSTRUSDT",
    "DYMUSDT",
    "LABUSDT",
    "MAGMAUSDT",
    "POLUSDT",
    "SNXUSDT",
    "LTCUSDT",
    "PLUMEUSDT",
    "HOMEUSDT",
    "CLOUDUSDT",
    "CARVUSDT",
    "METISUSDT",
    "LIGHTUSDT",
    "ASRUSDT",
    "MTLUSDT",
    "CCUSDT",
    "HUSDT",
    "AUSDT",
    "MONUSDT",
    "AVAAIUSDT",
    "RENDERUSDT",
    "SCRUSDT",
    "AWEUSDT",
    "FLUXUSDT",
    "DYDXUSDT",
    "KAVAUSDT",
    "KSMUSDT",
    "ALCHUSDT",
    "ETHBTCUSDT",
    "FLRUSDT",
    "RLCUSDT",
    "DOTUSDT",
    "RVNUSDT",
    "QNTUSDT",
    "ANKRUSDT",
    "AGLDUSDT",
    "CRVUSDT",
    "CVCUSDT",
    "ALGOUSDT",
    "LUNA2USDT",
    "MEMEUSDT",
    "SCUSDT",
    "ENJUSDT",
    "NEOUSDT",
    "BATUSDT",
    "IOSTUSDT",
  ],
};
