export const BACKTEST_SYMBOLS_COUNT = 3000;
export const BACKTEST_START_BALANCE = 100;
export const BACKTEST_CANDLE_INTERVAL = 60;
export const BACKTEST_CANDLES_COUNT = 3 * 365 * 24;
export const BACKTEST_COMMISSION_RATE = 0.001;
export const BACKTEST_FUNDING_RATE_ESTIMATE = 0.0001;
