import dotenv from "dotenv";

dotenv.config();

export const apiKey = process.env.API_KEY;
export const apiSecret = process.env.API_SECRET;

export const MAX_POSITIONS = 25;
export const MAX_RISK = 0.035;
export const LEVERAGE = 10;

export const BACKTEST_SYMBOLS_COUNT = 3000;
export const BACKTEST_START_BALANCE = 100;
export const BACKTEST_CANDLE_INTERVAL = 60;
export const BACKTEST_CANDLES_COUNT = 3 * 365 * 24;
export const BACKTEST_COMMISSION_RATE = 0.001;
export const BACKTEST_FUNDING_RATE_ESTIMATE = 0.0001;

export const STRATEGY_SMA_PERIOD_SLOW = 200;
export const STRATEGY_SMA_PERIOD_FAST = 50;
export const STRATEGY_RSI_PERIOD = 14;
export const STRATEGY_RSI_OVERBOUGHT = 40;
export const STRATEGY_STOP_LOSS_DELTA = 0.1;
export const STRATEGY_TAKE_PROFIT_DELTA = 0.17;
export const STRATEGY_ATR_PERIOD = 14;
export const STRATEGY_ATR_MULTIPLIER = 2.2;
export const PAUSE_CANDLES_AFTER_LOSS = 5;

export const WIN_SYMBOLS = [
  "FLOCKUSDT",
  "EDGEUSDT",
  "DIAUSDT",
  "CLANKERUSDT",
  "FIDAUSDT",
  "LITUSDT",
  "DOODUSDT",
  "POLYXUSDT",
  "PNUTUSDT",
  "BROCCOLIUSDT",
  "LSKUSDT",
  "FOLKSUSDT",
  "CUSDT",
  "GRIFFAINUSDT",
  "PROVEUSDT",
  "EPICUSDT",
  "RONINUSDT",
  "HIVEUSDT",
  "OLUSDT",
  "SAGAUSDT",
  "BLESSUSDT",
  "SEIUSDT",
  "1000FLOKIUSDT",
  "GRASSUSDT",
  "10000QUBICUSDT",
  "HANAUSDT",
  "1000TAGUSDT",
  "CHILLGUYUSDT",
  "EIGENUSDT",
  "SCRTUSDT",
  "AXSUSDT",
  "ARPAUSDT",
  "EGLDUSDT",
  "BOBBOBUSDT",
  "COAIUSDT",
  "DOLOUSDT",
  "NIGHTUSDT",
  "ALTUSDT",
  "ARIAUSDT",
  "BIGTIMEUSDT",
  "ERAUSDT",
  "PHAUSDT",
  "BANANAUSDT",
  "PYRUSDT",
  "BSVUSDT",
  "ADAUSDT",
  "0GUSDT",
  "DRIFTUSDT",
  "PUMPBTCUSDT",
  "1000NEIROCTOUSDT",
  "NOMUSDT",
  "1000CATUSDT",
  "PYTHUSDT",
  "HOLOUSDT",
  "OPENUSDT",
  "OPNUSDT",
  "KASUSDT",
  "GUNUSDT",
  "GLMUSDT",
  "HPOS10IUSDT",
  "LUMIAUSDT",
  "CTCUSDT",
  "ACXUSDT",
  "MIRAUSDT",
  "HIGHUSDT",
  "HYPEUSDT",
  "ASPUSDT",
  "SKRUSDT",
  "HMSTRUSDT",
  "DYMUSDT",
  "LABUSDT",
  "MAGMAUSDT",
  "POLUSDT",
  "SNXUSDT",
  "LTCUSDT",
  "PLUMEUSDT",
  "HOMEUSDT",
  "CLOUDUSDT",
  "CARVUSDT",
  "METISUSDT",
  "LIGHTUSDT",
  "ASRUSDT",
  "MTLUSDT",
  "CCUSDT",
  "HUSDT",
  "AUSDT",
  "MONUSDT",
  "AVAAIUSDT",
  "RENDERUSDT",
  "SCRUSDT",
  "AWEUSDT",
  "FLUXUSDT",
  "DYDXUSDT",
  "KAVAUSDT",
  "KSMUSDT",
  "ALCHUSDT",
  "ETHBTCUSDT",
  "FLRUSDT",
  "RLCUSDT",
  "DOTUSDT",
  "RVNUSDT",
  "QNTUSDT",
  "ANKRUSDT",
  "AGLDUSDT",
  "CRVUSDT",
  "CVCUSDT",
  "ALGOUSDT",
  "LUNA2USDT",
  "MEMEUSDT",
  "SCUSDT",
  "ENJUSDT",
  "NEOUSDT",
  "BATUSDT",
  "IOSTUSDT",
];
