export const leverage = 10;
export const timeFrame = 15;
export const takeProfitRatio = 0.15; //
export const stopLossRatio = 0.1; //
export const pullbackThreshold = 0.04; // Уровень отката: 4%
export const riskPercentage = 0.02;
export const candleCountAnalize = 4;
export const checkStrategyInterval = 10;
export const orderLimit = 50 / riskPercentage / 100;
