export const leverage = 10;
export const timeFrame = 15;
export const takeProfitRatio = 0.2; //
export const stopLossRatio = 0.1; //
export const pullbackThreshold = 0.05; // Уровень отката: 4%
export const riskPercentage = 0.005;
export const candleCountAnalize = 4;
export const checkStrategyInterval = 10;
export const orderLimit = 30 / riskPercentage / 100;
